### ISSUE TITLE
Index.collection is nil

### ISSUE THREAD

**Issue by sobrinho** [hummingbird-me/typesensual#3]
Hi there!

I created my index and then tried to used it but it doesn't work since:

```ruby
class MyIndex < Typesensual::Index
  schema do
    field 'name', type: 'string'
  end
end

MyIndex.collection
#=> nil

MyIndex.create!
#=> #<Typesensual::Collection:0x00005571433884e8 @collection={"fields"=>[{"name"=>"name", "type"=>"string"}], "name"=>"my@1706022998"}>

MyIndex.collection
#=> nil
```

What's wrong here?

**Comment by NuckChorris** [comment]
You need to `MyIndex.update_alias!(MyIndex.create!)` so that the index alias is pointed at the current collection — `MyIndex.collection` references the alias instead of a specific collection

Do you think it would help if I made `MyIndex.collection` raise an exception when the alias doesn't exist? 🤔

**Comment by sobrinho** [comment]
Yep, probably better!

I wonder where it would be the best place to call `MyIndex.update_alias!(MyIndex.create!)` if every single Index would need this call before being used 🤔

**Comment by NuckChorris** [comment]
There's [some rake tasks](https://github.com/hummingbird-me/typesensual/blob/main/lib/typesensual/rake_helper.rb) to handle creating the collection and pointing an alias at it, as well as a `.reindex!` method which recreates the indices and points the alias at it, but perhaps a `reindex` task would be helpful? Reindexing is largely supposed to be a rare, manual task (vs incremental updates on record change) so I think rake is the right place for it, but it's clear that the current tasks are not clear or easily automated (the output of collection creation needs to be used as the input for the alias updating, not great). I should probably also clarify the readme on this
