### ISSUE TITLE
Nested classes doesn't work

### ISSUE THREAD

**Issue by sobrinho** [hummingbird-me/typesensual#4]
Typesense doesn't support slashes on the index name, it returns a 404:

```ruby
require 'typesensual'

module MyModule
  class MyIndex < Typesensual::Index
  end
end

MyModule::MyIndex.alias_name
#=> "my_module/my"
```

To workaround, I'm overriding that method:

```ruby
    def self.alias_name
      super.gsub('/', '::')
    end
```

That way the generated alias name works as expected.

**Comment by NuckChorris** [comment]
Hmmm I wonder if this is actually true or if it just needs to be URL-encoded as a segment, let me check with the Typesense team!

**Comment by NuckChorris** [comment]
Great news, they actually fixed this upstream in typesense/typesense-ruby#33 so updating to the latest typesense gem (2.0.0) should resolve it 🎉
