### ISSUE TITLE
Allow to use .multi as .load for long queries

### ISSUE THREAD

**Issue by sobrinho** [hummingbird-me/typesensual#5]
Hi,

We have a big query that raises that error:

```
Typesense::Error::RequestMalformed (Query string exceeds max allowed length of 4000. Use the /multi_search end-point for larger payloads.)
```

To workaround, we changed this:

```ruby
MyIndex.search(query: query, query_by: query_by).facets(facets).sort(sort).filter(filter).page(page).per(per).load
```

To

```ruby
Typesensual::Search.multi(MyIndex.search(query: query, query_by: query_by).facets(facets).sort(sort).filter(filter).page(page).per(per))[0]
```

Which is pretty much the same but using the multi endpoint.

We could have a helper method on the Search object to use this:

```ruby
MyIndex.search(query: query, query_by: query_by).facets(facets).sort(sort).filter(filter).page(page).per(per).multi
```

Instead of

```ruby
MyIndex.search(query: query, query_by: query_by).facets(facets).sort(sort).filter(filter).page(page).per(per).load
```

I would even say that we could rescue from that error automatically or even always use the multi endpoint since it is more robust.

What are your thoughts?

**Comment by NuckChorris** [comment]
Sorry I didn't see your issues until now, I like the idea of making it automatically switch the underlying query method between search vs multi_search based on length! PR welcome, otherwise I'll look into adding that soon!

**Comment by NuckChorris** [comment]
On further thought, since this is server-side there's really no reason to ever use the single-search `GET` endpoint 😅 I'll switch it to using the multi-search endpoint for all queries
